# Generated by Django 2.0.5 on 2018-05-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='image',
            field=models.ImageField(default='photos/default.png', upload_to='photos'),
        ),
    ]
