# Generated by Django 2.0.5 on 2018-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_productos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(default='photos/default.png', upload_to='InventarioCEI/static/photos/'),
        ),
    ]
