# Generated by Django 2.0.5 on 2018-05-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_auto_20180504_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='status',
            field=models.IntegerField(choices=[(1, 'Habilitado'), (0, 'Deshabilitado')], default=1),
        ),
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(default='img/photos/default.png', upload_to='img/photos/'),
        ),
    ]
