# Generated by Django 2.0 on 2018-05-18 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20180517_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='No tiene usuario asignado', max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date borrowed')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Productos')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.CharField(default='No tiene usuario asignado.', max_length=200),
        ),
    ]
