# Generated by Django 2.0 on 2018-05-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20180518_2024'),
        ('Inventario', '0005_auto_20180518_1605'),
    ]

    operations = [
    ]
