# Generated by Django 2.0.3 on 2018-06-01 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_espacio_reserva_espacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='No tiene usuario asignado.', max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date start')),
                ('date_end', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date finish')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Espacio')),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva_espacio',
            name='space',
        ),
        migrations.DeleteModel(
            name='Reserva_Espacio',
        ),
    ]
