# Generated by Django 2.0.5 on 2018-06-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_auto_20180601_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponible'), (0, 'En Prestamo'), (2, 'En Reparacion'), (3, 'Perdido')], default=1),
        ),
    ]
