# Generated by Django 2.0.6 on 2018-06-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponible'), (0, 'Ocupado'), (2, 'En Reparacion')], default=1),
        ),
    ]
